# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Rubber Duck Yourself
email: jake@dabapps.com
description: >- # this means to ignore newlines until "baseurl:"
  Rubber duck debugging chat bot
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jakesidsmith.com/rubber-duck-yourself" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

sass:
  sass_dir: _scss

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - .nvmrc
  - .browserslistrc
  - .prettierrc.json
  - webpack.config.js
  - tsconfig.json
  - tsconfig.dist.json
  - tslint.json
  - src/
  - coverage/
  - scripts/
  - types/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
